spring:
  mail:
    host: email.xxx.com
    port: 25
    username: email
    password: pwd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        imap:
          host: email.xxx.com
          port: 143
        store:
          protocol: imap
